name: daily eth rate

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  report:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
      - run: yarn install
        working-directory: packages/eth
      - name: check
        run: npx ts-node daily-eth-rate.ts
        working-directory: packages/eth
        env:
          NODE_ENV: production
          F2_POOL: ${{ secrets.F2_POOL }}
          GIST_TOKEN: ${{ secrets.GIST_TOKEN }}
          GIST_KEY: ${{ secrets.ETH_GIST_KEY }}
