name: daily eth

on:
  schedule:
    - cron: '0 5 * * *'
  workflow_dispatch:

jobs:
  report:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
      - run: yarn install
        working-directory: packages/eth
      - name: check
        run: node daily-eth.js
        working-directory: packages/eth
        env:
          NODE_ENV: production
          TG_CHAT_ID_ETH_MINE_REPORT: ${{ secrets.TG_CHAT_ID_ETH_MINE_REPORT }}
          TG_TOKEN: ${{ secrets.TG_TOKEN }}
          BN_TOKEN: ${{ secrets.BN_TOKEN }}
          OTS_AK: ${{ secrets.OTS_AK }}
          OTS_SK: ${{ secrets.OTS_SK }}
